### PR TITLE
Fix linter/static checks

### PR DESCRIPTION
**Pull request by Alexmac22347**

### CODE REVIEW

**Comment by Alexmac22347** [comment]
the linting test on jenkins is setting commit status now, @briellelaw I changed the branch protection rule so that it has to pass the static_analysis test

**Review by briellelaw — APPROVED** [review]
mvp, lgtm

**Comment by brunorodd** [comment]
i love you alex

**Review by brunorodd — APPROVED** [review]
Alex is the GOAT. lgtm

**Comment by brunorodd** [comment]
brillee do the honors

**Pull request merged**
