### PR TITLE
Fixed mock_sensors playback functionality

### PR DESCRIPTION
**Pull request by jahn18**

### CODE REVIEW

**Comment by jahn18** [comment]
I did a little digging into why the playback function on the mock_sensors script was getting those ridiculous values with latitude and longitude--it had to do with the endianness of the value. It's a mini-fix, but now the latitude and longitude range around 3000~5000, which makes more sense :)

**Review by brunorodd — APPROVED** [review]
I trust your judgment boss.

**Comment by jahn18** [comment]
One more change: I found that what was being outputted from bbb_canbus_listener wasn't consistent with my record_time_series_table script, so I fixed that up by just implementing what was on frame_parser.h in `src/uccm/ `dir. Now the sensor data is outputting the same things (You can confirm with "sample_time_series_data.csv")

**Review by briellelaw — APPROVED** [review]
Thanks for looking into this! 
rn tests are using the real can bus, but these fixes will definitely be useful for future testing

**Pull request merged**
